# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d97e54ef0bdb39bc2a7486a39a87300407af7c301f06f3f067dcf2c9e180c0e22e0109d788979f3feaa81d9d8af1ad857d3b190ccee9e9a14693deb9d2cef32f

test:
  secret_key_base: cda5ec175983e7013cf99807a3366ed493876fa080e9d636c3f274580503b990ed375d7606f487d1e70307658b1b4fd1fd8253edc3ebe52dec1d6ed7b8d919b2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
